stages:
  - load_testing

start_authorization_test:
  stage: authorization_test
  script:
    - mvn gatling:test -Dgatling.simulationClass=gatling.users.authorization.AuthorizationAdminTest
    - mvn gatling:test -Dgatling.simulationClass=gatling.users.authorization.AuthorizationUserTest

start_registration_test:
  stage: registration_test
  script:
    - mvn gatling:test -Dgatling.simulationClass=gatling.users.registration.RegistrationTest

start_loading_avatar_test:
  stage: loading_avatar_test
  script:
    - mvn gatling:test -Dgatling.simulationClass=gatling.users.loading_avatar.LoadingAvatarTest

test:
  stage: load_testing
  script:
    - echo "Running load tests"
  parallel:
    matrix:
      - JOB: "start_authorization_test"
      - JOB: "start_registration_test"
      - JOB: "start_loading_avatar_test"