stages:
  - load_testing

load_tests:
  stage: load_testing
  tags:
    - ${GENERATOR}
  before_script:
    - apt-get update && apt-get install -y maven default-jdk
  script:
    - echo "Запуск теста с параметрами:"
    - echo "JOB NAME - ${JOB_NAME}"
    - echo "GATLING SCRIPT - ${GATLING_SCRIPT}"
    - echo "${GATLING_SCRIPT}" > ./script.sh
    - chmod +x ./script.sh
    - ./script.sh
  artifacts:
    paths:
      - ./target/gatling/
    expire_in: 1 week
  rules:
    - if: '$GENERATOR != "" && $JOB_NAME != "" && $GATLING_SCRIPT != ""'
