version: '3.8'

services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.8.6
    ports:
      - "8086:8086"
      - "2003:2003"
    volumes:
      - ./monitoring/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    networks:
      - monitoring-net

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge
