{
 "title": "Gatling Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "data_source", "query": "influxdb" },
   { "name": "measurement", "query": { "query": "SHOW MEASUREMENTS" } },
   { "name": "send_interval", "query": "10,15,30,60,120,300" }
  ]
 },
 "panels": [
  {
   "title": "Module USERS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS UC (OK)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "$tag_group",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "group::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "query": "SELECT mean(\"count\")  / 10 FROM \"gatling\" WHERE (\"request\"::tag = 'allRequests') AND $timeFilter GROUP BY time(10s) fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / ${send_interval}" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "group::tag", "operator": "!=", "value": "allRequests" },
        { "condition": "AND", "key": "status::tag", "operator": "=", "value": "ok" }
       ]
      }
     ]
    },
    {
     "title": "RPS UC (ERROR)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "$tag_group",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "group::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "query": "SELECT mean(\"count\")  / 10 FROM \"gatling\" WHERE (\"request\"::tag = 'allRequests' AND \"status\"::tag = 'ko') AND $timeFilter GROUP BY time(10s) fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / ${send_interval}" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "group::tag", "operator": "!=", "value": "allRequests" },
        { "condition": "AND", "key": "status::tag", "operator": "=", "value": "ko" }
       ]
      }
     ]
    },
    {
     "title": "RPS UC (OK)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "$tag_request",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "request::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "query": "SELECT mean(\"count\")  / 10 FROM \"gatling\" WHERE (\"request\"::tag = 'allRequests') AND $timeFilter GROUP BY time(10s) fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / ${send_interval}" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "request::tag", "operator": "!=", "value": "allRequests" },
        { "condition": "AND", "key": "status::tag", "operator": "=", "value": "ok" }
       ]
      }
     ]
    },
    {
     "title": "RPS UR (RROR)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "$tag_request",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "request::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "query": "SELECT mean(\"count\")  / 10 FROM \"gatling\" WHERE (\"request\"::tag = 'allRequests' AND \"status\"::tag = 'ko') AND $timeFilter GROUP BY time(10s) fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / ${send_interval}" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "request::tag", "operator": "!=", "value": "allRequests" },
        { "condition": "AND", "key": "status::tag", "operator": "=", "value": "ko" }
       ]
      }
     ]
    },
    {
     "title": "50%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_request",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "request::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "percentiles50" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "request::tag", "operator": "!=", "value": "allRequests" }
       ]
      }
     ]
    },
    {
     "title": "75%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_request",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "request::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "percentiles75" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "request::tag", "operator": "!=", "value": "allRequests" }
       ]
      }
     ]
    },
    {
     "title": "95%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_request",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "request::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "percentiles95" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "request::tag", "operator": "!=", "value": "allRequests" }
       ]
      }
     ]
    },
    {
     "title": "99%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_request",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "request::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "percentiles99" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "request::tag", "operator": "!=", "value": "allRequests" }
       ]
      }
     ]
    }
   ]
  }
 ]
}