{
 "title": "Gatling InfluxDB",
 "tags": [
  "Gatling",
  "InfluxDB",
  "Graphite"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "send_interval", "query": "10,15,30,60" },
   { "name": "system", "query": "users,petstore" },
   { "name": "load_generator", "query": "localhost" }
  ]
 },
 "panels": [
  {
   "title": "Action Users (Scenarios)",
   "type": "timeseries",
   "description": "Количество активных виртуальных пользователей за интервал времени (10с).",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "VUs" } },
   "targets": [
    {
     "alias": "$tag_scenario",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "scenario::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling.users",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "scenario::tag", "operator": "=~", "value": "/.*${system}.*/" },
      { "condition": "AND", "key": "loadGenerator::tag", "operator": "=~", "value": "/^$load_generator$/" },
      { "condition": "AND", "key": "scenario::tag", "operator": "!=", "value": "allUsers" }
     ]
    }
   ]
  },
  {
   "title": "Total Action Users",
   "type": "timeseries",
   "description": "Общее количество активных пользователей за интервал времени (10с).",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "VUs" } },
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling.users",
     "query": "SELECT mean(\"active\") FROM \"gatling.users\" WHERE (\"scenario\"::tag =~ /.*${system}.*/ AND \"loadGenerator\"::tag =~ /^$load_generator$/ AND \"scenario\"::tag != 'allUsers') AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "scenario::tag", "operator": "=~", "value": "/.*${system}.*/" },
      { "condition": "AND", "key": "loadGenerator::tag", "operator": "=~", "value": "/^$load_generator$/" },
      { "condition": "AND", "key": "scenario::tag", "operator": "!=", "value": "allUsers" }
     ]
    }
   ]
  },
  {
   "title": "SUCCESSFUL %",
   "type": "gauge",
   "description": "Процент успешных запросов в процентах.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT 100 * sum(\"ok\") / sum(\"all\")\nFROM \n    (SELECT sum(\"count\") as \"all\" FROM \"gatling\" WHERE (\"status\" = 'all' AND \"request\" =~ /.*${system}*./ AND \"loadGenerator\"::tag =~ /^$load_generator$/) AND $timeFilter GROUP BY time($__interval) fill(null)),\n    (SELECT sum(\"count\") as \"ok\" FROM \"gatling\" WHERE (\"status\" = 'ok' AND \"request\" =~ /.*${system}*./ AND \"loadGenerator\"::tag =~ /^$load_generator$/) AND $timeFilter GROUP BY time($__interval) fill(null))\n"
    }
   ]
  },
  {
   "title": "ERROR %",
   "type": "gauge",
   "description": "Процент неудачных запросов в процентах.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT 100 * sum(\"ko\") / sum(\"all\")\nFROM \n    (SELECT sum(\"count\") as \"all\" FROM \"gatling\" WHERE (\"status\" = 'all' AND \"request\" =~ /.*${system}*./ AND \"loadGenerator\"::tag =~ /^$load_generator$/) AND $timeFilter GROUP BY time($__interval) fill(null)),\n    (SELECT sum(\"count\") as \"ko\" FROM \"gatling\" WHERE (\"status\" = 'ko' AND \"request\" =~ /.*${system}*./ AND \"loadGenerator\"::tag =~ /^$load_generator$/) AND $timeFilter GROUP BY time($__interval) fill(null))\n"
    }
   ]
  },
  {
   "title": "Total RPS (OK)",
   "type": "timeseries",
   "description": "Количество успешных запросов в секунду.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "Total (UC)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / ${send_interval}" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group::tag", "operator": "=~", "value": "/.*${system}.*/" },
      { "condition": "AND", "key": "status::tag", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "loadGenerator::tag", "operator": "=~", "value": "/^$load_generator$/" },
      { "condition": "AND", "key": "count::field", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Total (UR)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / ${send_interval}" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "request::tag", "operator": "=~", "value": "/.*${system}.*/" },
      { "condition": "AND", "key": "status::tag", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "loadGenerator::tag", "operator": "=~", "value": "/^$load_generator$/" },
      { "condition": "AND", "key": "count::field", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Total RPS (KO)",
   "type": "timeseries",
   "description": "Количество неудачных запросов в секунду.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / ${send_interval}" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "request::tag", "operator": "=~", "value": "/.*${system}.*/" },
      { "condition": "AND", "key": "status::tag", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "loadGenerator::tag", "operator": "=~", "value": "/^$load_generator$/" },
      { "condition": "AND", "key": "count::field", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Summary UC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Summary UC",
     "type": "table",
     "description": "Статистика по UC:\n\nrequest - Название запросов;\n\nTotal - Общее количество запросов;\n\nOK - Количество успешных запросов;\n\nKO - Количество неудачных запросов;\n\nOK% - Процент успешных запросов;\n\nKO% - Процент неудачных запросов;\n\nTPS - Запросов в секунду;\n\nMin - Минимальное время ответа;\n\n50th pct - 50-й прецентиль;\n\n75th pct - 75-й прецентиль;\n\n95th pct - 95-й прецентиль;\n\n99th pct - 99-й прецентиль;\n\nMax - Максимальное время ответов;\n\nMean - Среднее время ответа;\n\nStd Dev - Стандартное отклонение (показывает, насколько сильно разбросаны времена отклика запросов относительно среднего значения).",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "query": "SELECT sum(\"ok\") + sum(\"ko\") as \"Total\",\n       sum(\"ok\") as \"OK\",\n       sum(\"ko\") as \"KO\",\n       100 * sum(\"ok\") / (sum(\"ko\") + sum(\"ok\")) as \"OK%\",\n       100 * sum(\"ko\") / (sum(\"ko\") + sum(\"ok\")) as \"KO%\",\n       (mean(\"TPS_OK\") + mean(\"TPS_KO\")) / (${send_interval}) as \"TPS\",\n       min(\"Min\") / 1000 as \"Min\",\n       mean(\"50th pct\") / 1000 as \"50th pct\",\n       mean(\"75th pct\") / 1000 as \"75th pct\",\n       mean(\"95th pct\") / 1000 as \"95th pct\",\n       mean(\"99th pct\") / 1000 as \"99th pct\",\n       max(\"Max\") / 1000 as \"Max\",\n       mean(\"Mean\") / 1000 as \"Mean\",\n       mean(\"Std Dev\") / 1000 as \"Std Dev\"\nFROM\n(\n    SELECT\n      mean(\"count\") as \"ok\",\n      mean(\"count\") as \"TPS_OK\",\n      min(\"min\") as \"Min\",\n      mean(\"percentiles50\") as \"50th pct\",\n      mean(\"percentiles75\") as \"75th pct\",\n      mean(\"percentiles95\") as \"95th pct\",\n      mean(\"percentiles99\") as \"99th pct\",\n      max(\"max\") as \"Max\",\n      mean(\"mean\") as \"Mean\",\n      mean(\"stdDev\") as \"Std Dev\"\n    FROM \"gatling\"\n    WHERE (\"status\" = 'ok' AND \"group\" =~ /.*${system}.*/) AND $timeFilter\n    GROUP BY time($__interval), \"group\", \"request\" fill(null)\n),\n(\n    SELECT\n      mean(\"count\") as \"ko\",\n      mean(\"count\") as \"TPS_KO\",\n      min(\"min\") as \"Min\",\n      mean(\"percentiles50\") as \"50th pct\",\n      mean(\"percentiles75\") as \"75th pct\",\n      mean(\"percentiles95\") as \"95th pct\",\n      mean(\"percentiles99\") as \"99th pct\",\n      max(\"max\") as \"Max\",\n      mean(\"mean\") as \"Mean\",\n      mean(\"stdDev\") as \"Std Dev\"\n    FROM \"gatling\"\n    WHERE (\"status\" = 'ko' AND \"group\" =~ /.*${system}.*/) AND $timeFilter\n    GROUP BY time($__interval), \"group\", \"request\" fill(null)\n)\nWHERE $timeFilter\nGROUP BY \"group\", \"request\" fill(null)\n\n\n",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "RPS UC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS UC (OK)",
     "type": "timeseries",
     "description": "Количество успешно обработанных запросов в секунду.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 351 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "$tag_group",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "group::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / ${send_interval}" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "group::tag", "operator": "=~", "value": "/.*${system}.*/" },
        { "condition": "AND", "key": "status::tag", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "loadGenerator::tag", "operator": "=~", "value": "/^$load_generator$/" },
        { "condition": "AND", "key": "count::field", "operator": ">", "value": "0" },
        { "condition": "AND", "key": "group::tag", "operator": "=", "value": "uc_users_authentication_admin" }
       ]
      }
     ]
    },
    {
     "title": "RPS UC (KO)",
     "type": "timeseries",
     "description": "Количество неудачных запросов в секунду.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 351 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "$tag_group",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "group::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / ${send_interval}" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "group::tag", "operator": "=~", "value": "/.*${system}.*/" },
        { "condition": "AND", "key": "status::tag", "operator": "=", "value": "ko" },
        { "condition": "AND", "key": "loadGenerator::tag", "operator": "=~", "value": "/^$load_generator$/" },
        { "condition": "AND", "key": "count::field", "operator": ">", "value": "0" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Latency UC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "50th pct UC",
     "type": "timeseries",
     "description": "50-й прецентиль.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_group",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "group::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "query": "SELECT sum(\"percentiles50\")\nFROM (\nSELECT max(\"percentiles50\") AS \"percentiles50\"\nFROM \"gatling\" \n    WHERE (\"group\"::tag =~ /.*${system}.*/ AND \"loadGenerator\"::tag =~ /^$load_generator$/) AND $timeFilter\n    GROUP BY time(10s), \"group\"::tag, \"request\"::tag fill(null)\n)\nGROUP BY time(10s), \"group\"::tag fill(null)",
       "select": [
        [
         { "params": [ "percentiles50" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "group::tag", "operator": "=~", "value": "/.*${system}.*/" },
        { "condition": "AND", "key": "loadGenerator::tag", "operator": "=~", "value": "/^$load_generator$/" }
       ]
      }
     ]
    },
    {
     "title": "75th pct UC",
     "type": "timeseries",
     "description": "75-й прецентиль.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_group",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "group::tag" ], "type": "tag" },
        { "params": [ "request::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "query": "SELECT sum(\"percentiles75\")\nFROM (\nSELECT max(\"percentiles75\") AS \"percentiles75\"\nFROM \"gatling\" \n    WHERE (\"group\"::tag =~ /.*${system}.*/ AND \"loadGenerator\"::tag =~ /^$load_generator$/) AND $timeFilter\n    GROUP BY time(10s), \"group\"::tag, \"request\"::tag fill(null)\n)\nGROUP BY time(10s), \"group\"::tag fill(null)",
       "select": [
        [
         { "params": [ "percentiles75" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "group::tag", "operator": "=~", "value": "/.*${system}.*/" },
        { "condition": "AND", "key": "loadGenerator::tag", "operator": "=~", "value": "/^$load_generator$/" }
       ]
      }
     ]
    },
    {
     "title": "95th pct UC",
     "type": "timeseries",
     "description": "95-й прецентиль.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_group",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "group::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "query": "SELECT sum(\"percentiles95\")\nFROM (\nSELECT max(\"percentiles95\") AS \"percentiles95\"\nFROM \"gatling\" \n    WHERE (\"group\"::tag =~ /.*${system}.*/ AND \"loadGenerator\"::tag =~ /^$load_generator$/) AND $timeFilter\n    GROUP BY time(10s), \"group\"::tag, \"request\"::tag fill(null)\n)\nGROUP BY time(10s), \"group\"::tag fill(null)",
       "select": [
        [
         { "params": [ "percentiles95" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "group::tag", "operator": "=~", "value": "/.*${system}.*/" },
        { "condition": "AND", "key": "loadGenerator::tag", "operator": "=~", "value": "/^$load_generator$/" }
       ]
      }
     ]
    },
    {
     "title": "99th pct UC",
     "type": "timeseries",
     "description": "99-й прецентиль.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_group",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "group::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "query": "SELECT sum(\"percentiles99\")\nFROM (\nSELECT max(\"percentiles99\") AS \"percentiles99\"\nFROM \"gatling\" \n    WHERE (\"group\"::tag =~ /.*${system}.*/ AND \"loadGenerator\"::tag =~ /^$load_generator$/) AND $timeFilter\n    GROUP BY time(10s), \"group\"::tag, \"request\"::tag fill(null)\n)\nGROUP BY time(10s), \"group\"::tag fill(null)",
       "select": [
        [
         { "params": [ "percentiles99" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "group::tag", "operator": "=~", "value": "/.*${system}.*/" },
        { "condition": "AND", "key": "loadGenerator::tag", "operator": "=~", "value": "/^$load_generator$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Summary UR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Summary UR",
     "type": "table",
     "description": "Статистика по UC:\n\nrequest - Название запросов;\n\nTotal - Общее количество запросов;\n\nOK - Количество успешных запросов;\n\nKO - Количество неудачных запросов;\n\nOK% - Процент успешных запросов;\n\nKO% - Процент неудачных запросов;\n\nTPS - Запросов в секунду;\n\nMin - Минимальное время ответа;\n\n50th pct - 50-й прецентиль;\n\n75th pct - 75-й прецентиль;\n\n95th pct - 95-й прецентиль;\n\n99th pct - 99-й прецентиль;\n\nMax - Максимальное время ответов;\n\nMean - Среднее время ответа;\n\nStd Dev - Стандартное отклонение (показывает, насколько сильно разбросаны времена отклика запросов относительно среднего значения).",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "query": "SELECT sum(\"ok\") + sum(\"ko\") as \"Total\",\n       sum(\"ok\") as \"OK\",\n       sum(\"ko\") as \"KO\",\n       100 * sum(\"ok\") / (sum(\"ko\") + sum(\"ok\")) as \"OK%\",\n       100 * sum(\"ko\") / (sum(\"ko\") + sum(\"ok\")) as \"KO%\",\n       (mean(\"TPS_OK\") + mean(\"TPS_KO\")) / (${send_interval}) as \"TPS\",\n       min(\"Min\") / 1000 as \"Min\",\n       mean(\"50th pct\") / 1000 as \"50th pct\",\n       mean(\"75th pct\") / 1000 as \"75th pct\",\n       mean(\"95th pct\") / 1000 as \"95th pct\",\n       mean(\"99th pct\") / 1000 as \"99th pct\",\n       max(\"Max\") / 1000 as \"Max\",\n       mean(\"Mean\") / 1000 as \"Mean\",\n       mean(\"Std Dev\") / 1000 as \"Std Dev\"\nFROM\n(\n    SELECT\n      mean(\"count\") as \"ok\",\n      mean(\"count\") as \"TPS_OK\",\n      min(\"min\") as \"Min\",\n      mean(\"percentiles50\") as \"50th pct\",\n      mean(\"percentiles75\") as \"75th pct\",\n      mean(\"percentiles95\") as \"95th pct\",\n      mean(\"percentiles99\") as \"99th pct\",\n      max(\"max\") as \"Max\",\n      mean(\"mean\") as \"Mean\",\n      mean(\"stdDev\") as \"Std Dev\"\n    FROM \"gatling\"\n    WHERE (\"status\" = 'ok' AND \"request\" =~ /.*${system}.*/) AND $timeFilter\n    GROUP BY time($__interval) fill(null)\n),\n(\n    SELECT\n      mean(\"count\") as \"ko\",\n      mean(\"count\") as \"TPS_KO\",\n      min(\"min\") as \"Min\",\n      mean(\"percentiles50\") as \"50th pct\",\n      mean(\"percentiles75\") as \"75th pct\",\n      mean(\"percentiles95\") as \"95th pct\",\n      mean(\"percentiles99\") as \"99th pct\",\n      max(\"max\") as \"Max\",\n      mean(\"mean\") as \"Mean\",\n      mean(\"stdDev\") as \"Std Dev\"\n    FROM \"gatling\"\n    WHERE (\"status\" = 'ko' AND \"request\" =~ /.*${system}.*/) AND $timeFilter\n    GROUP BY time($__interval) fill(null)\n)\nWHERE $timeFilter\nGROUP BY \"request\" fill(null)",
       "select": [
        [
         { "params": [ "mean" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "RPS UR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS UR (OK)",
     "type": "timeseries",
     "description": "Количество успешно обработанных запросов в секунду.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 442 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "$tag_request",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "request::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / ${send_interval}" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "request::tag", "operator": "=~", "value": "/.*${system}.*/" },
        { "condition": "AND", "key": "status::tag", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "loadGenerator::tag", "operator": "=~", "value": "/^$load_generator$/" },
        { "condition": "AND", "key": "count::field", "operator": ">", "value": "0" }
       ]
      }
     ]
    },
    {
     "title": "RPS UR (KO)",
     "type": "timeseries",
     "description": "Количество неудачных запросов в секунду.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 442 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "$tag_request",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "request::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / ${send_interval}" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "request::tag", "operator": "=~", "value": "/.*${system}.*/" },
        { "condition": "AND", "key": "status::tag", "operator": "=", "value": "ko" },
        { "condition": "AND", "key": "loadGenerator::tag", "operator": "=~", "value": "/^$load_generator$/" },
        { "condition": "AND", "key": "count::field", "operator": ">", "value": "0" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Latency UR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "50th pct UR",
     "type": "timeseries",
     "description": "50-й прецентиль.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_request",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "request::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "percentiles50" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "request::tag", "operator": "=~", "value": "/.*${system}.*/" },
        { "condition": "AND", "key": "loadGenerator::tag", "operator": "=~", "value": "/^$load_generator$/" }
       ]
      }
     ]
    },
    {
     "title": "75th pct UR",
     "type": "timeseries",
     "description": "75-й прецентиль.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_request",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "request::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "percentiles75" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "request::tag", "operator": "=~", "value": "/.*${system}.*/" },
        { "condition": "AND", "key": "loadGenerator::tag", "operator": "=~", "value": "/^$load_generator$/" }
       ]
      }
     ]
    },
    {
     "title": "95th pct UR",
     "type": "timeseries",
     "description": "95-й прецентиль.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_request",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "request::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "percentiles95" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "request::tag", "operator": "=~", "value": "/.*${system}.*/" },
        { "condition": "AND", "key": "loadGenerator::tag", "operator": "=~", "value": "/^$load_generator$/" }
       ]
      }
     ]
    },
    {
     "title": "99th pct UR",
     "type": "timeseries",
     "description": "99-й прецентиль.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_request",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "request::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gatling",
       "select": [
        [
         { "params": [ "percentiles99" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "request::tag", "operator": "=~", "value": "/.*${system}.*/" },
        { "condition": "AND", "key": "loadGenerator::tag", "operator": "=~", "value": "/^$load_generator$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}