apiVersion: 1

datasources:
  - name: vm
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    basicAuth: false
    isDefault: true
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
    editable: true